# Rules you can define for organize to execute
rules:
  # name of a single rule [any string]
  - name: Empty File
    # tags that you can give a rule
    # you can execute a single rule from a config file
    # by calling e.g. `organize run config --path <path to config> --tags Test::EmptyFile,Test::EmptyFolder`
    tags:
      # tags is a list containing of either [!custom, !always_run, !never_run]:
      # `!custom` following by a customized string
      #  `!always_run` hardcoded tag to always run this rule
      #  `!never_run` hardcoded tag to never run this rule
      - !custom Test::EmptyFile
    # enabling and disabling a single rule [true, false]
    enabled: true
    # the locations organize will apply the filters to
    locations:
      # `locations` is a list where each item is either
      # [!recursive, !non_recursive, !default_settings]
      - !recursive
        path: crates\organize-rs_core\tests\fixtures\filters\empty_file
        # depth for this location, seen from `path`
        # how deep organize should traverse the file system
        max_depth: 1
    # filter groups, that organize operates with
    # each filter group can contain many filters
    filter_groups:
      # the whole group can be excluded, which means that
      # files/folders matching this filter will not be acted upon.
      # Say, we want to match no empty files
      - exclude: no
        mode: must_apply
        # target kind, to what organize should apply the filters
        # to in this location, can be either [files, folders, both]
        target: files # TODO: think if target is an attribute of FilterGroup or Location, what are the implications
        filters:
          - empty
    actions:
      - !preview trash
